#kics-scan disable=a88baa34-e2ad-44ea-ad6f-8cac87bc7c71
services:
  nginx_manager:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    container_name: nginx_manager
    hostname: nginx_manager
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    # /data/nginx/custom is the directory of custom nginx conf inside container
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

    networks:
      - my_network
    # Default admin user
    # Email:    admin@example.com Pass: changeme
    #* To reset password visit https://www.reddit.com/r/nginxproxymanager/comments/zm3ewq/nginx_proxy_managerlost_password_to_web_ui/
networks:
  my_network:
    driver: bridge
    name: my_network
