#kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8
services:
  xray:
    image: ghcr.io/xtls/xray-core:latest
    ports:
      - "10808:10808"
    container_name: xray
    hostname: xray
    restart: unless-stopped
    volumes:
      - ./:/etc/xray
