services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    ports:
      - :5000
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
    restart: unless-stopped
    # volumes:
    #   - ./registery:/var/lib/registry:rw
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-check-certificate",
          "--spider",
          "--quiet",
          "http://localhost:5000",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
    name: my_network
