#kics-scan disable=8c978947-0ff6-485c-b0c2-0bfca6026466
services:
  # uncomment this section and comment out the mysql section to use postgres instead of mysql
  #postgres:
  #restart: unless-stopped
  #image: postgres:14
  #hostname: postgres
  #volumes:
  #  - semaphore-postgres:/var/lib/postgresql/data
  #environment:
  #  POSTGRES_USER: semaphore
  #  POSTGRES_PASSWORD: semaphore
  #  POSTGRES_DB: semaphore
  # if you wish to use postgres, comment the mysql service section below
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my_network
  semaphore:
    hostname: semaphore
    container_name: semaphore
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    env_file:
      - .env
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${MYSQL_PASSWORD}
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      SEMAPHORE_LDAP_ACTIVATED: "no" # if you wish to use ldap, set to: 'yes'
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: "636"
      SEMAPHORE_LDAP_NEEDTLS: "yes"
      SEMAPHORE_LDAP_DN_BIND: "uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net"
      SEMAPHORE_LDAP_PASSWORD: "ldap_bind_account_password"
      SEMAPHORE_LDAP_DN_SEARCH: "dc=local,dc=example,dc=com"
      SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
      TZ: UTC
    depends_on:
      - mysql # for postgres, change to: postgres
    networks:
      - my_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-check-certificate",
          "--spider",
          "--quiet",
          "http://localhost:80",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  semaphore-mysql: # to use postgres, switch to: semaphore-postgres

networks:
  my_network:
    name: my_network
    driver: bridge
