services:
  server:
    image: ghcr.io/bluewave-labs/checkmate-backend-mono-multiarch:latest
    restart: always
    hostname: checkmate
    container_name: checkmate
    pull_policy: always
    environment:
      - UPTIME_APP_API_BASE_URL=${UPTIME_APP_API_BASE_URL}
      - UPTIME_APP_CLIENT_HOST=${UPTIME_APP_CLIENT_HOST}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - REDIS_URL=${REDIS_URL}
      - CLIENT_HOST=${CLIENT_HOST}
      - JWT_SECRET=${JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.checkmate.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.checkmate.entrypoints=websecure"
      - "traefik.http.routers.checkmate.tls=true"
      - "traefik.http.routers.checkmate.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.checkmate.loadbalancer.server.port=52345"
    networks:
      - my_network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    hostname: mongodb_checkmate
    container_name: mongodb_checkmate
    restart: always
    command: [ "mongod", "--quiet", "--bind_ip_all" ]
    volumes:
      - ./mongo/data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })", "--quiet" ]
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - my_network

networks:
  my_network:
    name: my_network
