# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/
# Create files .devskim.json .checkov.yml kics.config
APPLY_FIXES: all
COPYPASTE_JSCPD_DISABLE_ERRORS: true
SPELL_CSPELL_DISABLE_ERRORS: true
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SPELL_LYCHEE_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
