# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in

APPLY_FIXES: all
COPYPASTE_JSCPD_DISABLE_ERRORS: true
SPELL_CSPELL_DISABLE_ERRORS: true
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SPELL_LYCHEE_DISABLE_ERRORS: true
REPOSITORY_DEVSKIM_ARGUMENTS:
  - "--ignore-rule-ids DS162092" # Ignore passing 127.0.0.1 as debug code
REPOSITORY_KICS_ARGUMENTS:
  - "--exclude-queries '610e266e-6c12-4bca-9925-1ed0cd29742b,ce76b7d0-9e77-464d-b86f-c5c48e03e22d,8c978947-0ff6-485c-b0c2-0bfca6026466,451d79dc-0588-476a-ad03-3c7f0320abb3'"
REPOSITORY_CHECKOV_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
