repos:
  # - repo: https://github.com/oxsecurity/megalinter
  #   rev: v7.10.0
  #   hooks:
  #     - id: megalinter-incremental
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-json
  # - id: pretty-format-json
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-shebang-scripts-are-executable
# # Python security
# - repo: https://github.com/PyCQA/bandit
#   rev: 1.7.8
#   hooks:
#   - id: bandit
# # Git security
# - repo: https://github.com/gitguardian/gg-shield
#   rev: v1.25.0
#   hooks:
#   - id: ggshield
#   - id: ggshield-iac
#   - id: ggshield-sca
#   - id: docker-ggshield
