repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: v8.1.0 # Git tag specifying the hook, not mega-linter-runner, version
    hooks:
      - id: megalinter-incremental # Faster, less thorough
        stages:
          - pre-commit
      - id: megalinter-full # Slower, more thorough
        stages:
          - pre-push

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.262 # change to tag or sha
    hooks:
      - id: checkov
        # - id: checkov_container
        # - id: checkov_diff
        # - id: checkov_diff_container
        # - id: checkov_secrets
        # - id: checkov_secrets_container

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: check-shebang-scripts-are-executable

  # Python security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit

  # Git security
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.32.1
    hooks:
      - id: ggshield
      - id: ggshield-iac
      - id: ggshield-sca
