services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3001"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  my_network:
    driver: bridge
    name: my_network
