#kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8
services:
  marzneshin:
    # to create an admin inside container run python3
    # marzneshin-cli.py admin create --sudo
    image: dawsh/marzneshin:latest
    restart: always
    hostname: marzneshin
    container_name: marzneshin
    env_file: .env
    ports:
      - 8000:8000
    # network_mode: host
    environment:
      SQLALCHEMY_DATABASE_URL: "sqlite:////var/lib/marzneshin/db.sqlite3"
    volumes:
      - ./dashboard-data:/var/lib/marzneshin

  marznode:
    # https://azavaxhuman.github.io/MarzbanInboundGenerator/v2/ To generate xray_config
    image: dawsh/marznode:latest
    restart: always
    hostname: marznode
    container_name: marznode
    # network_mode: host
    ports:
      - "50000-50050:50000-50050"
      - $SERVICE_PORT:$SERVICE_PORT
    env_file:
      - .env
    environment:
      SERVICE_ADDRESS: "0.0.0.0"
      INSECURE: "True"
      XRAY_EXECUTABLE_PATH: "/usr/local/bin/xray"
      XRAY_ASSETS_PATH: "/usr/local/lib/xray"
      XRAY_CONFIG_PATH: "/var/lib/marznode/xray_config.json"
      SSL_KEY_FILE: "./server.key"
      SSL_CERT_FILE: "./server.cert"
    volumes:
      - ./node-data:/var/lib/marznode
