#kics-scan disable=8c978947-0ff6-485c-b0c2-0bfca6026466,ae5b6871-7f45-42e0-bb4c-ab300c4d2026
services:
  iventoy:
    build:
      args:
        - IVENTOY=1.0.19
      context: .
      dockerfile: Dockerfile
    container_name: iventoy
    hostname: iventoy
    restart: always
    privileged: true #must be true
    ports:
      - 26000:26000
      - 16000:16000
      - 10809:10809
      - 67:67/udp
      - 69:69/udp
    volumes:
      - ./isos:/app/iso
      - iventoy_config:/app/data
      - ./log:/app/log
    environment:
      - AUTO_START_PXE=true # optional, true by default
    healthcheck:
      test: ["CMD", "./iventoy.sh", "-R", "start"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  iventoy_config:
