---
services:
  n8n:
    #* On first start up go to /setup path to setup n8n instance
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - 5678:5678
    hostname: n8n
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    environment:
      - N8N_SECURE_COOKIE=false #* This will allow http connections remove this to be more secure
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:5678"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 3s
volumes:
  n8n_data:
