#! Set pg-password env variable before deploying
services:
  postgres-server:
    image: postgres:17
    container_name: postgres-server
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${pg-password}
      POSTGRES_DB: zabbix
    networks:
      - my_network
    restart: unless-stopped

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps
    container_name: zabbix-snmptraps
    volumes:
      - /zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
    networks:
      - my_network
    ports:
      - "162:1162/udp"
    restart: unless-stopped

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql
    container_name: zabbix-server-pgsql
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${pg-password}
      POSTGRES_DB: zabbix
      ZBX_ENABLE_SNMP_TRAPS: "true"
    networks:
      - my_network
    ports:
      - "10051:10051"
    volumes_from:
      - zabbix-snmptraps
    restart: unless-stopped

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql
    container_name: zabbix-web-nginx-pgsql
    environment:
      ZBX_SERVER_HOST: zabbix-server-pgsql
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ${pg-password}
      POSTGRES_DB: zabbix
    networks:
      - my_network
    ports:
      - "8443:8443"
      - "8085:8080"
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
