services:
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    restart: always
    # user: root #* needed to work properly
    networks:
      - my_network
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
networks:
  my_network:
    driver: bridge
    name: my_network
