services:
  x-ui-main:
    image: alireza7/x-ui:latest
    hostname: xui
    container_name: xui
    ports:
      - :54321 # Web UI
      - 2096:2096 # Subscription
      # inbound
      - 12000-12030:12000-12030 # Socks
      - 12000-12030:12000-12030/udp # Wireguard
      # outbound
      - 51820:51820 # Surfshark
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - ./db:/etc/x-ui/
      - ./cert:/root/cert/
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    name: my_network
