services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - :3000
    volumes:
      - grafana:/var/lib/grafana:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`${grafana_domain}`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.rule=Host(`${grafana_domain}`)"
      - "traefik.http.routers.grafana-secure.tls.certresolver=myresolver"

    networks:
      - my_network
volumes:
  grafana: {}
networks:
  my_network:
    driver: bridge
    name: my_network
