services:
  web-check:
    image: lissy93/web-check
    container_name: webcheck
    hostname: webcheck
    ports:
      - 3000:3000
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - GOOGLE_CLOUD_API_KEY=value  # https://cloud.google.com/api-gateway/docs/authenticate-api-keys
      - REACT_APP_SHODAN_API_KEY=value  # https://account.shodan.io/
      - REACT_APP_WHO_API_KEY=value # https://whoapi.com/
      - SECURITY_TRAILS_API_KEY=value # https://securitytrails.com/corp/api
      - CLOUDMERSIVE_API_KEY=value  # https://account.cloudmersive.com/
      - TRANCO_USERNAME=value # https://tranco-list.eu/
      - TRANCO_API_KEY=value  # https://tranco-list.eu/
      - URL_SCAN_API_KEY=value  # https://urlscan.io/
      - BUILT_WITH_API_KEY=value  # https://api.builtwith.com/
      - TORRENT_IP_API_KEY=value  # https://iknowwhatyoudownload.com/en/api/
networks:
  my_network:
    driver: bridge
    name: my_network
