#kics-scan disable=d6355c88-1e8d-49e9-b2f2-f8a1ca12c75b,1c1325ff-831d-43a1-973e-839ae57dfcc0,698ed579-b239-4f8f-a388-baa4bcb13ef8
#Ignore kics health check since it's built in
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    container_name: watchtower
    hostname: watchtower
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
    name: my_network
