#! Set database env variables before running the container
services:
  broker:
    container_name: paperless-redis
    hostname: paperless-redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - "$Home/OneDrive/My Software/Paperless/redis_data:/data"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 5s
      interval: 30s
      retries: 5
      timeout: 3s

  db:
    container_name: paperless-db
    hostname: paperless-db
    image: docker.io/library/postgres:17
    restart: unless-stopped
    volumes:
      - "$Home/OneDrive/My Software/Paperless/pgdata:/var/lib/postgresql/data"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -p 5432 -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
    # environment:
    #   POSTGRES_DB: paperless
    #   POSTGRES_USER: paperless
    #   POSTGRES_PASSWORD:
    #   paperless

  webserver:
    container_name: paperless-webserver
    hostname: paperless-webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    # user: root # Requiered if specified more than one language
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - "$Home/OneDrive/My Software/Paperless/data:/usr/src/paperless/data"
      - "$Home/OneDrive/My Software/Paperless/media:/usr/src/paperless/media"
      - "$Home/OneDrive/My Software/Paperless/export:/usr/src/paperless/export"
      - "$Home/OneDrive/My Software/Paperless/consume:/usr/src/paperless/consume"
    env_file: docker-compose.env
    environment:
      #* Set the following variable to the URL of your paperless instance. needed for nginx
      PAPERLESS_URL: https://yourdomain.com
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
