#kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8

---

services:
  webdav:
    image: derkades/webdav
    volumes: ./data:/data
    ports: 8080:80
    environment:
      USERNAME: # user
      PASSWORD: # Yo4Nup5uvDmo587P8xPpqT
    restart: unless-stopped
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
    name: my_network
