#kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8
services:
  webdav:
    image: bytemark/webdav
    hostname: webdav
    container_name: webdav
    restart: always
    ports:
      - :80
    env_file:
      - .env
    volumes:
      - /karing:/var/lib/dav
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
    name: my_network
