services:
  webdav:
    image: bytemark/webdav
    hostname: webdav
    container_name: webdav
    restart: always
    ports:
      - :80
    env_file:
      - .env
    volumes:
      - /karing:/var/lib/dav
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
    name: my_network
