services:
  oblivion:
    container_name: oblivion
    hostname: oblivion
    image: ghcr.io/bepass-org/warp-plus:sha-b525aed3a9614df54b1501a9b8f68c328fa32517
    command: -b 0.0.0.0:${PORT} --scan --gool
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    environment:
      - PORT
