#kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8
services:
  webserver:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./cache/:/cache/:rw # Cache
      - ./conf/:/etc/nginx/conf.d/:ro # Nginx conf
      - ./certbot/www:/var/www/certbot/:ro # certbot webroot
      - ./certbot/letsencrypt/:/etc/letsencrypt/live/:ro # SSL certs
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/letsencrypt/:/etc/letsencrypt/:rw
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
    name: my_network
