services:
  wordpress:
    depends_on:
      - wordpress_db
    container_name: WordPress
    image: wordpress
    restart: always
    ports:
      - :80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: ${WordPress_db_user}
      WORDPRESS_DB_PASSWORD: ${WordPress_Pass}
      WORDPRESS_DB_NAME: WordPress_db
    volumes:
      - ./WordPress:/var/www/html
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      #- "traefik.http.services.WordPress_service.loadbalancer.server.port: 80"
      - "traefik.http.routers.WordPress.entrypoints=web"
      - "traefik.http.routers.WordPress.rule=Host(`${WordPress_Domain}`)"
      - "traefik.http.routers.WordPress-secure.tls=true"
      - "traefik.http.routers.WordPress-secure.entrypoints=websecure"
      - "traefik.http.routers.WordPress-secure.rule=Host(`${WordPress_Domain}`)"
      - "traefik.http.routers.WordPress-secure.tls.certresolver=myresolver"
  wordpress_db:
    container_name: wordpress_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: WordPress_db
      MYSQL_USER: ${WordPress_db_user}
      MYSQL_PASSWORD: ${WordPress_Pass}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./WordPress_database:/var/lib/mysql
    networks:
      - my_network
networks:
  my_network:
    name: my_network
    driver: bridge
