#kics-scan disable=ae5b6871-7f45-42e0-bb4c-ab300c4d2026,1c1325ff-831d-43a1-973e-839ae57dfcc0

services:
  cadvisor:
    # prometheus endpoint is at http://cadvisor:8080/metrics
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    privileged: true
    networks:
      - my_network
    devices:
      - /dev/kmsg
