#kics-scan disable=8c978947-0ff6-485c-b0c2-0bfca6026466
services:
  jenkins:
    image: jenkins/jenkins
    hostname: jenkins
    container_name: jenkins
    restart: on-failure
    ports:
      - 8080:8080 # Panel port
      - 50000:50000 # Agent port
    volumes:
      - jenkins_volume:/var/jenkins_home
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:50000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  jenkins_volume:
networks:
  my_network:
    driver: bridge
    name: my_network
