#kics-scan disable=8c978947-0ff6-485c-b0c2-0bfca6026466
services:
  jenkins:
    image: jenkins/jenkins
    hostname: jenkins
    container_name: jenkins
    restart: on-failure
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_volume:/var/jenkins_home
    networks:
      - my_network
volumes:
  jenkins_volume:
networks:
  my_network:
    driver: bridge
    name: my_network
