




include ../Makefile


setup: docker
	echo "To manage outline server download outline manager from:"
	echo "https://getoutline.org/"
	echo "Remember To save API key"
	# Install script
	sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
