services:
  hiddify:
    image: hiddify
    build: ./hiddify-config
    ports:
      - 443:443
      - 80:80
    # privileged: true
    # cap_add:
    #   - NET_ADMIN
    volumes:
      - ./hiddify-panel/hiddifypanel.db:/opt/hiddify-manager/hiddify-panel/hiddifypanel.db
      - ./Hiddify/ssl/:/opt/hiddify-manager/ssl/
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
    name: my_network
