services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096/tcp # is used by default for HTTP traffic. You can change this in the dashboard.
      - 8920:8920/tcp # is used by default for HTTPS traffic. You can change this in the dashboard.
      - 1900:1900/udp # is used for service auto-discovery. This is not configurable.
      - 7359:7359/udp # is also used for auto-discovery. This is not configurable.
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ${path}/media
        target: /media
      - type: bind
        source: ${path}/media2
        target: /media2
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: ${path}/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      my_network:
      # my_macvlan:
      #   ipv4_address: 10.1.0.6
networks:
  my_network:
  # my_macvlan:
  #   name: my_macvlan
  #   driver: macvlan
  #   driver_opts:
  #     parent: eth0
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 10.1.0.0/24
  #         gateway: 10.1.0.1
