# Cloudflared download links
# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/#linux
#kics-scan disable=698ed579-b239-4f8f-a388-baa4bcb13ef8
# kics ignore health ckeck
services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared
    command: tunnel --url "${DOMAIN}:${PORT}" --edge-ip-version auto --no-autoupdate -protocol http2
    networks:
      - my_network
    container_name: cloudflared-tunnel
    restart: unless-stopped
    env_file:
      - .env

networks:
  my_network:
    driver: bridge
    name: my_network
