---
services:
  orb-docker:
    image: orbforge/orb:latest
    container_name: orb-sensor # Optional: Give the container a specific name
    # network_mode: host # Optional: alternatively you can use 'bridge' mode and map ports :7443 and :5353
    ports:
      - :7443
      - :5353
    volumes:
      - ./orb-data:/root/.config/orb # Persists Orb configuration
    restart: unless-stopped # Ensures Orb restarts if it stops or on system reboot
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Enable auto-updates with Watchtower
      - "com.centurylinklabs.watchtower.scope=orb" # Scope for Watchtower to monitor
