services:
  activepieces:
    hostname: activepieces
    container_name: activepieces
    restart: unless-stopped
    image: activepieces/activepieces:latest
    # ports:
    # - "8080:80"
    volumes:
      - ./.activepieces:/root/.activepieces
    environment:
      - AP_QUEUE_MODE=MEMORY
      - AP_DB_TYPE=SQLITE3
      - AP_FRONTEND_URL="https:localhost:8080" # it is the public URL where the dashboard can be reached
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  my_network:
    driver: bridge
    name: my_network
