services:
  activepieces:
    image: activepieces/activepieces:latest
    # ports:
      # - "8080:80"
    volumes:
      - ./.activepieces:/root/.activepieces
    environment:
      - AP_QUEUE_MODE=MEMORY
      - AP_DB_TYPE=SQLITE3
      - AP_FRONTEND_URL="https:localhost:8080" # it is the public URL where the dashboard can be reached
