services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    hostname: crowdsec
    volumes:
      - "./crowdsec:/etc/crowdsec"
      - "./data/:/var/lib/crowdsec/data/"
      - "./log:/var/log:ro"
    restart: unless-stopped
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "cscli metrics"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  my_network:
    driver: bridge
    name: my_network
